FROM node:24-bookworm-slim AS build

ARG VITE_API_URL=/api/v1
ENV VITE_API_URL=${VITE_API_URL}

WORKDIR /app/frontend

COPY frontend/package*.json ./
RUN npm ci

COPY frontend /app/frontend

RUN npm run build


FROM nginx:1.27-alpine

COPY deploy/app/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/frontend/dist /usr/share/nginx/html

EXPOSE 80
